name: CI/CT workflow for Python libraries

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  ci-ct-job-for-python-libraries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Test Python repository
        uses: MGTheTrain/github-actions/.github/actions/test-python-repository@main
        with:
          PYTHON_VERSION: "3.11"
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORGANIZATION_ID: ${{ secrets.SNYK_ORGANIZATION_ID }}
          WORKING_DIRECTORY: ./