
name: CI/CT workflow for Python libraries packaged via pip

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  set_stage:
    name: Determine Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set revision_number by branch and semantic_version
        id: branch_check
        run: |
          echo "Running on branch ${{ github.base_ref }}"
          if [ "${{ github.base_ref }}" == "master" ]; then
            echo "revision_number=prerelease${{ github.run_number }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.base_ref }}" == "develop" ]; then
            echo "revision_number=dev${{ github.run_number }}" >> $GITHUB_OUTPUT
          fi
          semantic_version=$(cat version)
          echo "semantic_version=$semantic_version" >> $GITHUB_OUTPUT
      - name: Print Revision number
        run: echo "revision_number for branch '${{ github.base_ref }}' is '${{ steps.branch_check.outputs.revision_number }}'"
      - name: Print Semantic version
        run: echo "semantic_version for branch '${{ github.base_ref }}' is '${{ steps.branch_check.outputs.semantic_version }}'"
    outputs:
      revision_number: ${{ steps.branch_check.outputs.revision_number }}
      semantic_version: ${{ steps.branch_check.outputs.semantic_version }}
  ci-ct-job-for-rust-actix-web-services:
    runs-on: ubuntu-latest
    needs: [set_stage]
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: CI/CT Action for Rust Backend Services
        uses: MGTheTrain/github-actions/.github/actions/ci-ct-action-for-pip-packages@main
        with:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORGANIZATION_ID: ${{ secrets.SNYK_ORGANIZATION_ID }}
          CLOUDSMITH_REPOSITORY: ${{ secrets.CLOUDSMITH_REPOSITORY }}
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
          WORKING_DIRECTORY: ./
          PACKAGE_NAME: common_lib
          PACKAGE_VERSION: ${{ needs.set_stage.outputs.semantic_version }}.${{ needs.set_stage.outputs.revision_number }}